FROM wordpress:6.8-php8.1-apache

RUN docker-php-ext-install mysqli

# Install additional PHP extensions if needed
RUN apt-get update && apt-get install -y \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd